ALTER TABLE "Album"
ADD COLUMN "isVisible" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "autoShowOnRelease" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Song"
ADD COLUMN "isVisible" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "autoShowOnRelease" BOOLEAN NOT NULL DEFAULT false;
